### ISSUE TITLE
GUI not plotting

### ISSUE THREAD

**Issue by AbdelrhmanBassiouny** [joint-probability-trees/jpt-gui#2]
The GUI did not plot the probability distribution of a variable, which I am sure has instances with values.

![image](https://github.com/joint-probability-trees/jpt-gui/assets/36744004/29daf0e2-b4a3-42e6-947c-3d0fecc03617)

**Comment by tomsch420** [comment]
The domain of the "environment" variable most likely contains a python None value. Plotly handles None values by not plotting them. Due to None being the potentially only possible value it, your graph is empty.

**Comment by AbdelrhmanBassiouny** [comment]
> 

Yup, after replacing the None with the string 'None' it worked, thanks!
